#!/Users/kakao/.pyenv/shims/python
import os
import sys
import argparse

from common.font import *
from option.tmux import TmuxOption
from option.option import Option

if __name__=="__main__" :
    
    try :
        args = Option.get_args()
        if args.command == 'tmux': TmuxOption.handler(args)


    except KeyboardInterrupt: sys.exit(0)
    except IndexError: print(FAIL + 'Please check help page for the number of parameters\n' + END)
